services:
  postgres:
    container_name: 'algos-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=algos'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - 'C:/algos-db/data:/var/lib/postgresql'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d algos"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - algos-network
#  app:
#    container_name: 'algos-app'
#    image: hotking/algos-app:latest
#    ports:
#      - '8081:8081'
#    environment:
#      - SERVER_PORT=8081
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/algos
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=12345
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - algos-network
#    restart: unless-stopped
#    volumes:
#        - ./logs:/app/logs
#
networks:
  algos-network:
    driver: bridge
