services:
  postgres:
    container_name: 'algos-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=algos'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5433:5432'
    volumes:
      - '/~/algos/data:/var/lib/postgresql'