spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/algos
    username: 'postgres'
    password: '12345'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 100
  application:
    name: algos-db
server:
  port: 8081