page:
  size: 10
  num: 0
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/algos
    username: 'postgres'
    password: '12345'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          batch_size: 100
  application:
    name: algos-db
server:
  port: 8081
  address: 0.0.0.0