INSERT INTO algorithm (id, name, file_path, complexity_id) VALUES
(1, 'Быстрая сортировка', 'PlaceHolder1', 4),        -- O(n log n)
(2, 'Сортировка пузырьком', 'PlaceHolder2', 5),      -- O(n²)
(3, 'Бинарный поиск', 'PlaceHolder3', 2),            -- O(log n)
(4, 'Хеш-таблица (поиск)', 'PlaceHolder4', 1),       -- O(1) средний
(5, 'Двоичное дерево поиска', 'PlaceHolder5', 2),    -- O(log n)
(6, 'Сортировка слиянием', 'PlaceHolder6', 4),       -- O(n log n)
(7, 'Линейный поиск', 'PlaceHolder7', 3),            -- O(n)
(8, 'Стек (push/pop)', 'PlaceHolder8', 1),           -- O(1)
(9, 'Очередь (enqueue/dequeue)', 'PlaceHolder9', 1), -- O(1)
(10, 'Граф (BFS)', 'PlaceHolder10', 3),               -- O(n + m)
(11, 'Поиск в глубину (DFS)', 'PlaceHolder11', 3),    -- O(n + m)
(12, 'Сортировка выбором', 'PlaceHolder12', 5),       -- O(n²)
(13, 'Пирамидальная сортировка', 'PlaceHolder13', 4), -- O(n log n)
(14, 'Алгоритм Дейкстры', 'PlaceHolder14', 4),        -- O((n + m) log n)
(15, 'Алгоритм Флойда', 'PlaceHolder15', 5);          -- O(n³)