INSERT INTO algorithm (id, name, file_path, complexity_id) VALUES
(1, 'Быстрая сортировка', 'algos/quick-sort.md', 4),        -- O(n log n)
(2, 'Сортировка пузырьком', 'algos/bubble-sort.md', 5),      -- O(n²)
(3, 'Бинарный поиск', 'algos/binary-search.md', 2),            -- O(log n)
(4, 'Хеш-таблица (поиск)', 'algos/hash-table.md', 1),       -- O(1) средний
(5, 'Двоичное дерево поиска', 'algos/BST.md', 2),    -- O(log n)
(6, 'Сортировка слиянием', 'algos/merge-sort.md', 4),       -- O(n log n)
(7, 'Линейный поиск', 'algos/linear-search.md', 3),            -- O(n)
(8, 'Стек (push/pop)', 'algos/stack.md', 1),           -- O(1)
(9, 'Очередь (enqueue/dequeue)', 'algos/queue.md', 1), -- O(1)
(10, 'Граф (BFS)', 'algos/BFS.md', 3),               -- O(n + m)
(11, 'Поиск в глубину (DFS)', 'algos/DFS.md', 3),    -- O(n + m)
(12, 'Сортировка выбором', 'algos/selection-sort.md', 5),       -- O(n²)
(13, 'Пирамидальная сортировка', 'algos/heap-sort.md', 4), -- O(n log n)
(14, 'Алгоритм Дейкстры', 'algos/dijkstra.md', 4),        -- O((n + m) log n)
(15, 'Алгоритм Флойда', 'algos/floyd-warshall.md', 5);          -- O(n³)